import type { Metadata } from "next";
import "./globals.css";
import {Roboto} from "next/font/google";

const roboto_font = Roboto({
  weight: ["100", "400", "500", "700", "900"],
  display: "swap",
  fallback: ["Helvetica", "Arial", "sans-serif"],
  subsets: ['cyrillic', 'cyrillic-ext'],
  variable: "--default-font"
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto_font.variable} ${roboto_font.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
